# App Info
ios_app_id                                : 1407730596
appstore_link                             : https://itunes.apple.com/us/app/text-case/id1407730596?ls=1&mt=8&at=1010l4Hj
app_description                           : A simple utility that allows you to convert any text into various different formats.
enable_smart_app_banner                   : true

# Information About Yourself
your_name                                 : Chris Hannah                                
your_link                                 : https://chrishannah.me                     
your_city                                 : London                                
email_address                             : me@chrishannah.me    
facebook_username                         :                                           
instagram_username                        : lordchrishannah
twitter_username                          : chrishannah
github_username                           : chrishannah
youtube_username                          :

# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Tons of formats.
    description                           : There's a whopping number of 32 different formats to use!
    fontawesome_icon_name                 : random
    
  - title                                 : Share Extension
    description                           : It comes packed with an action extension that lets you select text anywhere in iOS, tap the Share button, and then you’ll find the “Convert Text” action. This will show you a preview of all available formats, and a simple tap on one of those will copy it to your clipboard, and you’ll be returned to the original app.
    fontawesome_icon_name                 : share
   
  - title                                 : Siri Shortcuts Support
    description                           : The "Format Text" action in Shortcuts will let you pass in any text as an input, choose one of the many formats, and then have the output passed back to you. This means that you can make use of all the functionality in Text Case, all from the Shortcuts app, and without it launching Text Case at all!
    fontawesome_icon_name                 : magic
    
  - title                                 : Customisation
    description                           : "There's a lot of customisation available in Text Case. The first one is the themes. There are three to choose from - Light, Dark, and Black. They change the whole interface of the app, and it also applies to the share extension. You can also choose to show/hide specific formats by navigating to the Settings page, and also change the order they are displayed in. This will apply to both the app, and the action extension. All settings will be synced across your iCloud devices."
    fontawesome_icon_name                 : edit
    
  - title                                 : Titles
    description                           : "There are four different title case standards you can choose from: AP, APA, Modern Language Association, and Chicago Manual of Style."
    fontawesome_icon_name                 : newspaper
    
  - title                                 : Common Transformations
    description                           : "All the basic text transformations are available: Uppercase, Lowercase, Capitalise, Capitalise Words, Sentence Case, and Reversed."
    fontawesome_icon_name                 : font

  - title                                 : Markdown
    description                           : "There are various different types of Markdown formats for you to use, such as Blockquotes, Code Blocks, Unordered Lists, and Ordered Lists. And you can also convert any Markdown formatted text into HTML!"
    fontawesome_icon_name                 : hashtag

  - title                                 : Custom Dictionary
    description                           : "When you use Title Case or Sentence case, you can specify a custom capitalisation using the custom dictionary. This is great for brand and product names, and makes the functionality of Title Case and Sentence case much more effective.There's a few handy nouns there to start you off."
    fontawesome_icon_name                 : book
   
  - title                                 : URLs
    description                           : You can encode text to URL formatting, and also decode it.
    fontawesome_icon_name                 : link
    
  - title                                 : Strip HTML
    description                           : You can extract any text from HTML code.
    fontawesome_icon_name                 : code
    
  - title                                 : Strip Whitespace
    description                           : Strip out all whitespace from text.
    fontawesome_icon_name                 : broom
    
  - title                                 : Trim Whitespace
    description                           : Remove any leading and trailing whitespace from text.
    fontawesome_icon_name                 : backspace
    
  - title                                 : Programming Formats
    description                           : "There's four programming inspired formats to choose from: Camel Case, Pascal Case, Snake Case, and Kebab Case."
    fontawesome_icon_name                 : keyboard
    
  - title                                 : Hashtags
    description                           : Convert any group of words into hashtags, for easy social use.
    fontawesome_icon_name                 : hashtag
   
  - title                                 : Mocking Spongebob
    description                           : Just for fun, you can convert any text in to Mocking Spongebob format, so you seem just a tad sarcastic.
    fontawesome_icon_name                 : grin-squint-tears
 
  - title                                 : Emoji
    description                           : For the times when you don't want to use plain text, you can let Text Case convert your words to appropriate Emoji!
    fontawesome_icon_name                 : grin-stars

  - title                                 : Rot13
    description                           : Have fun with your words by using the Rot13 cipher, to rotate each letter by 13 places.
    fontawesome_icon_name                 : sync

  - title                                 : Base64
    description                           : You can encode and decode any text to and from Base64 encoding.
    fontawesome_icon_name                 : laptop-code

  - title                                 : Clap Case
    description                           : Add 👏 clapping 👏 hands 👏 between 👏 each 👏 word.
    fontawesome_icon_name                 : sign-language
    
  - title                                 : Shuffled
    description                           : Randomise the order of text.
    fontawesome_icon_name                 : wind

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.2
topbar_title_color                        : "#ffffff"

cover_image                               : 
cover_overlay_color                       : "#F11A19"
cover_overlay_transparency                : 0.9

device_color                              : white

body_background_color                     : "ffffff"

link_color                                : "#F11A19"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#F11A19"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
