# App Info
ios_app_id                                : 1407730596                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://itunes.apple.com/us/app/text-case/id1407730596?ls=1&mt=8&at=1010l4Hj                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A simple utility that allows you to convert any text into various different formats.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Chris Hannah                                
your_link                                 : https://chrishannah.me                     
your_city                                 : London                                
email_address                             : me@chrishannah.me    
facebook_username                         :                                           
instagram_username                        : lordchrishannah
twitter_username                          : chrishannah
github_username                           : chrishannah
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Tons of formats.
    description                           : There's a whopping number of 19 different formats to use!
    fontawesome_icon_name                 : random
    
  - title                                 : Share Extension
    description                           : It comes packed with an action extension that lets you select text anywhere in iOS, tap the Share button, and then you’ll find the “Convert Text” action. This will show you a preview of all available formats, and a simple tap on one of those will copy it to your clipboard, and you’ll be returned to the original app.
    fontawesome_icon_name                 : share
   
  - title                                 : Siri Shortcuts Support
    description                           : All formats are available to be used with Siri Shortcuts. Every time you copy or share the result of a text conversion, iOS will be made aware and can suggest these actions to you in the future. You can also manually add a format to Siri by going tapping on Settings, and then the “Add to Siri” button at the bottom.
    fontawesome_icon_name                 : magic
    
  - title                                 : Customisation
    description                           : You can also choose to show/hide specific formats by navigating to the Settings page, and also change the order they are displayed in. This will apply to both the app, and the action extension. All settings will be synced across your iCloud devices.
    fontawesome_icon_name                 : edit
    
  - title                                 : Titles
    description                           : "There are four different title case standards you can choose from: AP, APA, Modern Language Association, and Chicago Manual of Style."
    fontawesome_icon_name                 : newspaper
    
  - title                                 : Common Transformations
    description                           : "All the basic text transformations are available: Uppercase, Lowercase, Capitalise, Capitalise Words, Sentence Case, and Reversed."
    fontawesome_icon_name                 : font
   
  - title                                 : URLs
    description                           : You can encode text to URL formatting, and also decode it.
    fontawesome_icon_name                 : link
    
  - title                                 : Strip HTML
    description                           : You can extract any text from HTML code.
    fontawesome_icon_name                 : code
    
  - title                                 : Programming Formats
    description                           : "There's four programming inspired formats to choose from: Camel Case, Pascal Case, Snake Case, and Kebab Case."
    fontawesome_icon_name                 : keyboard
    
  - title                                 : Hashtags
    description                           : Convert any group of words into hashtags, for easy social use.
    fontawesome_icon_name                 : hashtag
   
  - title                                 : Mocking Spongebob
    description                           : Just for fun, you can convert any text in to Mocking Spongebob format, so you seem just a tad sarcastic.
    fontawesome_icon_name                 : grin-squint-tears
 



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : https://i0.wp.com/blog.chrishannah.me/wp-content/uploads/2019/01/Image-2.png?w=3000&ssl=1                   # Replace with alternative image path or image URL.
cover_overlay_color                       : "#F11A19"
cover_overlay_transparency                : 0.4

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#F11A19"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#F11A19"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
