# App Info
ios_app_id                                : 1407730596
appstore_link                             : https://itunes.apple.com/us/app/text-case/id1407730596?ls=1&mt=8&at=1010l4Hj
app_description                           : Automatable Text Transformations
enable_smart_app_banner                   : true

# Information About Yourself
your_name                                 : Chris Hannah                                
your_link                                 : https://chrishannah.me                     
your_city                                 : London                                
email_address                             : me@chrishannah.me    
facebook_username                         :                                           
instagram_username                        : lordchrishannah
twitter_username                          : chrishannah
github_username                           : chrishannah
youtube_username                          :

# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Formats
    description                           : There are over 40 formats to choose from, including multiple title case standards, Markdown formats, cleansing tools, and a lot more.
    fontawesome_icon_name                 : font
    
  - title                                 : Complex Formats
    description                           : Some formats, such as Replace All Occurrences and Add Prefix, can be customised with parameters to make it even more personal.
    fontawesome_icon_name                 : keyboard
    
  - title                                 : Flows
    description                           : Combine multiple formats together to create a flow. These let you create more custom text transformations, which better fit your use case.
    fontawesome_icon_name                 : edit
    
  - title                                 : Shortcuts
    description                           : All of the built-in formats and user-created flows are available to use in the Shortcuts app. Even the more complex formats, which have their own dedicated actions.
    fontawesome_icon_name                 : magic
    
  - title                                 : iOS Share Extension
    description                           : It comes packed with an action extension that lets you select text anywhere in iOS, tap the Share button, and then you’ll find the “Convert Text” action. This will show you a preview of all available formats, and a simple tap on one of those will copy it to your clipboard, and you’ll be returned to the original app.
    fontawesome_icon_name                 : share
  
  - title                                 : macOS Action Extension
    description                           : Select a portion of text anywhere on macOS, and you'll be able to find the "Format Text" action in the share menu, which lets you directly format that text and have the result copied to your clipboard.
    fontawesome_icon_name                 : share

  - title                                 : Custom Dictionary
    description                           : "When you use Title Case or Sentence case, you can specify a custom capitalisation using the custom dictionary. This is great for brand and product names, and makes the functionality of Title Case and Sentence case much more effective.There's a few handy nouns there to start you off."
    fontawesome_icon_name                 : book

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#ffffff"

cover_image                               : 
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 1

device_color                              : black

body_background_color                     : "#111111"

link_color                                : "#F11A19"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#cccccc"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#cccccc"

feature_icons_foreground_color            : "#F11A19"
feature_icons_background_color            : "#333333"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#222222"

footer_text_color                         : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
